site_name: MS Project juhend
site_description: Github Page in Maksim repo TA-Kalender
site_url: https://maksimts-kool.github.io/TA-Kalender
repo_name: TA-Kalender
copyright: Copyright &copy; 2026 Maksim Tsikvasvili
docs_dir: docs
theme:
  name: material
  language: et
  palette:
    - scheme: default
      primary: green
      accent: indigo
  features:
    - navigation.instant
    - navigation.instant.progress
    - content.code.copy
    - navigation.footer
    - navigation.sections
    - navigation.path
  font:
    text: Poppins
    code: Roboto Mono
  icon:
    admonition:
      note: material/receipt-text-edit
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.blocks.caption
  - pymdownx.tabbed:
      alternate_style: true
nav:
  - Avaleht: index.md
  - Uue kalendri loomine: kalender.md
  - Arvutusvälja lisamine: arvutusvaljad.md
  - Diagrammi loomine: diagramm.md
plugins:
  - glightbox
extra_css:
  - stylesheets/extra.css
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/maksimts-kool
      name: Maksim on Github
    - icon: fontawesome/brands/telegram
      link: https://t.me/maksimts3
      name: Maksim on Telegram
